// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/requirejs-domready/domready.d.ts
declare module "domReady" {
    interface DomReady {
        (callback: () => any): DomReady;
        version: string;
    }

    let domReady: DomReady;

    export = domReady;
}
